<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-10-19 11:20

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('fluidhtml');
return array(
	'tx_fluidhtml_pi1' => $extensionPath . 'pi1/class.tx_fluidhtml_pi1.php',
);
